### ISSUE TITLE
Using wrong gomfweb?

### ISSUE THREAD

**Issue by veganstraightedge** [microformats/microformats-parser-website-go#4]
The deployed site 

https://go.microformats.io

doesn't seem to be using the HTML from the `gomfweb` command

https://github.com/willnorris/microformats/blob/master/cmd/gomfweb/main.go#L91-L158

***

I don't know Go well enough (at all!) to understand what's going wrong here.

**Comment by willnorris** [comment]
try redeploying now?  I updated the vendored deps in 85e74351084be75367bdce35994621b335dab4c9, though the `willnorris/go/microformats` package was already up to date, so I'm not sure this will make a difference.  I tried running locally, and it's picking up the correct style.  Maybe a caching issue somewhere?

**Comment by veganstraightedge** [comment]
Nope. Still old. I'm so confused.

Here's the build/deploy logs if that gives any clues

```
remote: -----> Go app detected
remote: -----> Checking vendor/vendor.json file.
remote:  !!    
remote:  !!    Deprecated or unsupported version of go (go1.8.7)
remote:  !!    See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
remote:  !!    
remote: -----> Using go1.8.7
remote: -----> Fetching any unsaved dependencies (govendor sync)
remote: -----> Running: go install -v -tags heroku github.com/indieweb/microformats-parser-website-go/vendor/willnorris.com/go/microformats/cmd/gomfweb 
remote: github.com/indieweb/microformats-parser-website-go/vendor/golang.org/x/net/html/atom
remote: github.com/indieweb/microformats-parser-website-go/vendor/golang.org/x/net/html
remote: github.com/indieweb/microformats-parser-website-go/vendor/willnorris.com/go/microformats
remote: github.com/indieweb/microformats-parser-website-go/vendor/willnorris.com/go/microformats/cmd/gomfweb
remote: -----> Discovering process types
remote:        Procfile declares types -> web
```

**Comment by willnorris** [comment]
okay, should be fixed now.  There was indeed an update to one of my packages that wasn't getting picked up for some reason.  I just deployed to https://gomfweb.herokuapp.com/ and it's using the latest style.

**Comment by willnorris** [comment]
also verified to be fixed on https://go.microformats.io/

**Comment by veganstraightedge** [comment]
So weird. Maybe a local cache (like you mentioned).

Thanks!
